feat: base methods of user router (TODO: tests for router and service)
SoftBananas/teamapp-backend pull request #10
Opened 2024-01-30 17:47 UTC by ONEPANTSU

2024-01-30 17:57 UTC, shamank reviewed
ну вот такое ревью

поясни потом за typeadapter

2024-01-30 17:57 UTC, shamank commented on src/api/http/user_router.py
> +        )
я предполагаю, что тут endpoint self.delete_user должен быть

2024-01-30 17:57 UTC, shamank commented on src/services/user/user_service.py
> +            logger.debug(f"Users found: {users}")
логи лучше писать же через "users found: %s" % users или что-то такое
на углубленном пайтоне поясняли, даже я помню :)))

2024-01-30 17:57 UTC, shamank commented on src/services/user/user_service.py
> +            return error
я вот кстати не знаю, как правильно на Python обрабатывать/формировать ошибку и передавать на другой уровень.

в гошке попроще и прямолинейней с этим

надо будет глянуть.

2024-01-30 17:57 UTC, shamank commented on src/services/user/user_service.py
>  from sqlalchemy.exc import IntegrityError
ошибки бд на уровне репозитория должны быть, по идеи

2024-02-04 10:47 UTC, shamank requested changes
А вообще либа fastapiusers стоит того?

2024-02-04 10:47 UTC, shamank commented on src/api/http/routers.py
> +        return self.routers
не очень как-то выглядит

особенно if router.endswith("_router")

2024-02-04 10:47 UTC, shamank commented on src/api/http/user/auth/verify_router.py
> +        return self.router
зачем делать столько роутеров? не проще объединить все их в один auth_router?

2024-02-04 10:47 UTC, shamank commented on src/services/user/user_service.py
> +
здесь совершенно верно ты подметил, что сервис напрямую не должен получать доступ к базе данных.

а еще ему конфиг не надо кидать.

а еще:
надо для jwt сделать какой-то JWTManager (описать его в utils, например), инициализировать его в App.py и в слой сервисов уже передавать сам JWTManager, а не конфиг

2024-02-04 10:47 UTC, shamank commented on src/app.py
> +        services = Services(repositories, self.config, self.database)
я описал это в другом файле, но тут продублирую:

базу данных вообще не в коем случае передавать не надо

вместо передачи конфига надо сделать что-то типо JWTManager и его передавать

2024-02-04 10:59 UTC, shamank commented on src/services/user/user_service.py
> +        super().__init__(repository)
ну мне всё так же не нравится, что ты передаешь сюда конфиг, хз
если думаешь, что это ок, то можешь оставить

2024-02-04 11:00 UTC, shamank commented on src/app.py
> +            self.include_router(router, prefix="/api/v1")
я потом тебе покажу еще один варик, как я вижу добавление роутеров

2024-02-04 11:02 UTC, shamank reviewed
как-то так

2024-02-12 18:57 UTC, ONEPANTSU commented on src/api/http/routers.py
> +        return self.routers
а мне наоборот показалось прикольным. ну типа прикинь, если роутеров оч много будет. а так это в одну строчку агрегация всех

2024-02-12 18:57 UTC, ONEPANTSU commented on src/api/http/user/auth/verify_router.py
> +        return self.router
можно, но просто они так логически разграничены - у каждого по несколько эндпоинтов

2024-02-12 18:57 UTC, ONEPANTSU commented on src/services/user/user_service.py
> +        super().__init__(repository)
я выделил отдельный "под-конфиг" для нужных секреток. (это точно лучше, чем еще 3 параметра передавать - мб их больше будет)
вот мне не оч нрав, что я фул конфиг в services передаю, но мб пригодится еще. надо подумать

2024-02-12 18:57 UTC, ONEPANTSU commented on src/app.py
> +            self.include_router(router, prefix="/api/v1")
оукей

2024-02-12 18:57 UTC, merged